window.TCFData = window.TCFData || {};
/* Remplacez audio:null par le chemin du fichier sonore lorsque vos audios seront disponibles. */
const coBank=[
 {theme:'Tourisme',transcription:"[Audio de démonstration] Bonjour, le musée de la ville sera fermé lundi matin pour maintenance. Il rouvrira à 13 h. Les billets achetés en ligne restent valables pour toute la journée.",questions:[
  {question:'Quand le musée rouvrira-t-il lundi ?',choix:['À 9 h','À 12 h','À 13 h','Le lendemain'],bonne:2,explication:'L’annonce indique que le musée rouvrira à 13 h.'},{question:'Que doivent faire les personnes ayant acheté un billet en ligne ?',choix:['Demander un remboursement','Revenir un autre jour','Acheter un nouveau billet','Utiliser leur billet dans la journée'],bonne:3,explication:'Les billets en ligne restent valables toute la journée.'},{question:'Pourquoi le musée ferme-t-il le matin ?',choix:['Pour une exposition','Pour maintenance','À cause de la météo','Pour une visite privée'],bonne:1,explication:'La fermeture est annoncée pour maintenance.'}]},
 {theme:'Technologie',transcription:"[Audio de démonstration] La ville lance une application qui permet de signaler un lampadaire en panne, un trottoir abîmé ou un dépôt sauvage. Les services municipaux reçoivent le signalement et l’utilisateur peut suivre son traitement. Cette application ne remplace pas les urgences.",questions:[
  {question:'À quoi sert l’application ?',choix:['À payer les impôts','À signaler des problèmes dans la ville','À réserver un stationnement','À appeler les urgences'],bonne:1,explication:'Elle sert à signaler des problèmes dans l’espace public.'},{question:'Que peut faire l’utilisateur après son signalement ?',choix:['Modifier les lois de la ville','Suivre le traitement du problème','Réparer lui-même le problème','Obtenir une réduction'],bonne:1,explication:'Il peut suivre le traitement de son signalement.'},{question:'Quelle précision donne la ville ?',choix:['L’application est payante','Elle fonctionne sans internet','Elle ne remplace pas les urgences','Elle est réservée aux touristes'],bonne:2,explication:'L’annonce précise que l’application ne remplace pas les urgences.'}]},
 {theme:'Transport',transcription:"[Audio de démonstration] En raison de travaux, la ligne 4 du métro ne circulera pas entre les stations Centre et Rivière samedi et dimanche. Des autobus de remplacement passeront toutes les dix minutes. Prévoyez environ quinze minutes de plus pour votre trajet.",questions:[
  {question:'Quand les travaux ont-ils lieu ?',choix:['Vendredi soir','Samedi et dimanche','Toute la semaine','Lundi matin'],bonne:1,explication:'Les travaux sont prévus samedi et dimanche.'},{question:'Quelle solution est proposée ?',choix:['Des taxis gratuits','Des trains supplémentaires','Des autobus de remplacement','Un itinéraire à pied'],bonne:2,explication:'Des autobus de remplacement circulent toutes les dix minutes.'},{question:'Quel conseil est donné aux voyageurs ?',choix:['Acheter un nouveau billet','Prévoir plus de temps','Éviter la station Centre','Voyager le matin'],bonne:1,explication:'Les voyageurs doivent prévoir quinze minutes de plus.'}]},
 {theme:'Santé',transcription:"[Audio de démonstration] Le centre de santé organise une journée de dépistage gratuit samedi prochain. Il est recommandé de prendre rendez-vous par téléphone, mais les personnes sans rendez-vous seront accueillies selon les places disponibles. Pensez à apporter votre carte d’assurance maladie.",questions:[
  {question:'Quelle activité organise le centre de santé ?',choix:['Une conférence payante','Un dépistage gratuit','Une vaccination obligatoire','Un cours de sport'],bonne:1,explication:'Il s’agit d’une journée de dépistage gratuit.'},{question:'Que conseille le centre ?',choix:['De venir uniquement sans rendez-vous','De prendre rendez-vous par téléphone','De payer sur internet','De venir avec un médecin'],bonne:1,explication:'Il est recommandé de prendre rendez-vous par téléphone.'},{question:'Quel document faut-il apporter ?',choix:['Une carte de bibliothèque','Une carte bancaire','Une carte d’assurance maladie','Un passeport'],bonne:2,explication:'L’annonce demande d’apporter la carte d’assurance maladie.'}]},
 {theme:'Culture',transcription:"[Audio de démonstration] La médiathèque accueillera l’écrivaine Nadia Benali jeudi à 18 h 30. Elle présentera son dernier roman puis répondra aux questions du public. L’entrée est libre, mais il faut retirer un billet gratuit à l’accueil avant la rencontre.",questions:[
  {question:'Qui vient à la médiathèque ?',choix:['Une musicienne','Une écrivaine','Une enseignante','Une journaliste'],bonne:1,explication:'La médiathèque accueille l’écrivaine Nadia Benali.'},{question:'Que fera-t-elle après la présentation ?',choix:['Elle vendra des livres','Elle donnera un cours','Elle répondra au public','Elle visitera la ville'],bonne:2,explication:'Elle répondra aux questions du public.'},{question:'Comment participer à la rencontre ?',choix:['Acheter un livre','Réserver un billet gratuit','Payer à l’entrée','S’inscrire en ligne uniquement'],bonne:1,explication:'Il faut retirer un billet gratuit à l’accueil.'}]}
];
const coLevels=['A1','A2','A2','B1','B1','B2','B2','B2','C1'];
window.TCFData.listening=Array.from({length:40},(_,index)=>{const source=coBank[index%coBank.length];return {id:`co${index+1}`,niveau:coLevels[index%coLevels.length],theme:source.theme,titre:`Série ${index+1} — ${source.theme}`,audio:null,transcription:source.transcription,questions:source.questions.map(q=>({...q}))}});
