window.TCFData = window.TCFData || {};
/* Banque extensible : chaque objet suit le format d'une question de compréhension écrite TCF. */
const ceBank=[
 {texte:"Maman,\nJe fais mes devoirs de mathématiques chez Louise. Je rentre à 21 heures.\nBises.\nPatrick",question:"Qu'est-ce que Patrick fait chez Louise ?",choix:["Il dort","Il travaille","Il joue","Il mange"],bonne:1,explication:"Patrick fait ses devoirs de mathématiques : il travaille."},
 {texte:"Attention\nCette semaine, l'accueil de l'université est fermé lundi toute la journée et vendredi après-midi.",question:"À quoi sert cette affiche ?",choix:["Annoncer un changement","Décrire un endroit","Donner un rendez-vous","Organiser une réunion"],bonne:0,explication:"L'affiche informe d'une modification temporaire des horaires de l'accueil."},
 {texte:"Aline, bonjour,\nC'est d'accord, rendez-vous avec les copines chez moi le 30 avril pour déjeuner.\nBisous.\nYvette",question:"Quelles sont les relations entre Aline et Yvette ?",choix:["Professionnelles","Familiales","Amicales","Commerciales"],bonne:2,explication:"Les mots « copines » et « Bisous » indiquent une relation amicale."},
 {texte:"Nous informons notre aimable clientèle que nous sommes actuellement en vacances jusqu'au dimanche 1er septembre. Nous aurons le plaisir de vous retrouver à partir du 2. Le magasin ouvrira comme tous les lundis à 11 h.",question:"Qu'apprend-on sur le magasin ?",choix:["Il va avoir de nouveaux horaires","Il va changer de propriétaire","Il va déménager en septembre","Il va fermer pendant l'été"],bonne:3,explication:"Le magasin est fermé pour les vacances jusqu'au 1er septembre."},
 {texte:"Salut Paul,\nJe t'écris du Canada. J'ai rencontré un étudiant mexicain. Je suis contente de parler ma langue avec lui, car l'Espagne me manque beaucoup ! En juin, nous suivons ensemble une formation en Italie.\nBisous.\nElsa",question:"Quelle est la nationalité d'Elsa ?",choix:["Canadienne","Espagnole","Italienne","Mexicaine"],bonne:1,explication:"Elsa dit que l'Espagne lui manque et qu'elle est contente de parler sa langue : elle est espagnole."},
 {texte:"Nous avons prévu quelques réparations dans l'appartement à la fin de la semaine. Veuillez nous excuser pour le bruit.\nM. et Mme Garnier",question:"Qu'est-ce que M. et Mme Garnier écrivent à leurs voisins ?",choix:["Ils vont bientôt déménager","Ils vont faire des travaux","Ils vont organiser une soirée","Ils vont recevoir de la visite"],bonne:1,explication:"Les réparations annoncées sont des travaux dans l'appartement."},
 {texte:"Un poste est libre dans votre association ? Le site propose de publier une annonce. Envoyez-nous la description du poste, le salaire et vos coordonnées.",question:"Que peuvent faire les associations sur ce site Internet ?",choix:["Offrir des emplois","Participer à un forum","Présenter leur action","Trouver de l'argent"],bonne:0,explication:"Le site permet de publier une annonce pour un poste libre."},
 {texte:"Madame,\nNous avons bien reçu votre demande de remboursement pour un billet de train. Vous nous avez envoyé le ticket de carte bancaire, mais nous avons aussi besoin d'une attestation de votre employeur.",question:"Quel document doit fournir la femme ?",choix:["Un document professionnel","Un titre de transport","Une enveloppe timbrée","Une somme d'argent"],bonne:0,explication:"Une attestation de l'employeur est un document professionnel."}
];
const ceThemes=['Vie quotidienne','Études','Relations sociales','Commerce','Voyage','Logement','Travail','Transport','Culture','Santé','Environnement','Technologie','Éducation','Tourisme','Économie'];
const ceLevels=['A1','A2','A2','B1','B1','B1','B2','B2','B2','B2','B2','C1'];
window.TCFData.reading=Array.from({length:40},(_,index)=>({
 id:`ce${index+1}`,niveau:ceLevels[index%ceLevels.length],theme:ceThemes[index%ceThemes.length],titre:`Série ${index+1} — ${ceThemes[index%ceThemes.length]}`,
 questions:Array.from({length:index===0?8:3},(_,q)=>({...ceBank[(index*3+q)%ceBank.length]}))
}));
