window.TCFData = window.TCFData || {};
const written = (task, rows) => rows.map(([id, level, theme, title, instruction, duration, tips, vocab, sample]) => ({id, competence:'expression-ecrite', tache:task, niveau:level, theme, titre:title, consigne:instruction, duree:duration, conseils:tips, vocabulaire:vocab, exemple:sample}));
window.TCFData.writing = [
  ...written(1,[
    ['ee11','A2','Loisirs','Proposer une sortie',"Vous écrivez à votre amie Léa. Proposez-lui de participer à une sortie culturelle ce week-end. Indiquez le lieu, l'heure et demandez-lui de répondre.",15,['Utilisez une formule d’appel et de fin.','Donnez trois informations pratiques.'],['proposer','être disponible','se retrouver'],"Bonjour Léa, samedi, je te propose d’aller à l’exposition de photographie au musée. On peut se retrouver à 14 h devant l’entrée. Es-tu disponible ? À bientôt !"],
    ['ee12','A2','Logement','Réserver un logement',"Vous souhaitez réserver une chambre pour deux nuits. Écrivez à l’hôtel pour demander le prix, l’heure d’arrivée possible et si le petit déjeuner est compris.",15,['Posez des questions précises.','Restez poli et concis.'],['réserver','une chambre double','compris'],"Bonjour, je voudrais réserver une chambre double pour deux nuits, du 12 au 14 juin. Quel est le tarif ? Puis-je arriver après 20 h ? Le petit déjeuner est-il compris ? Merci d’avance."],
    ['ee13','B1','Vie quotidienne','Une activité sportive',"Vous écrivez au centre sportif de votre ville pour obtenir des renseignements sur un cours de natation : horaires, prix et matériel nécessaire.",15,['Présentez votre demande.','Employez des questions variées.'],['renseignement','horaire','s’inscrire'],"Madame, Monsieur, je souhaite m’inscrire à un cours de natation pour adultes. Pourriez-vous m’indiquer les horaires, le tarif trimestriel et le matériel à prévoir ? Je vous remercie pour votre réponse."],
    ['ee14','B1','Événement','Inviter un voisin',"Votre quartier organise une journée de nettoyage du parc. Écrivez à un voisin pour l’inviter et expliquez l’intérêt de cette activité.",15,['Expliquez la date et le lieu.','Donnez une raison personnelle.'],['bénévole','ramasser','quartier'],"Bonjour Marc, samedi prochain, les habitants nettoient le parc du quartier à partir de 10 h. J’aimerais que tu viennes : ce sera utile pour les enfants et l’ambiance sera conviviale. Veux-tu participer avec moi ?"],
    ['ee15','B1','Transport','Objet oublié',"Vous avez oublié votre sac dans un autobus. Écrivez au service des objets trouvés : décrivez le sac, le trajet et vos coordonnées.",15,['Décrivez clairement l’objet.','Indiquez où et quand il a été perdu.'],['objet trouvé','trajet','contenir'],"Bonjour, j’ai oublié un sac à dos noir dans le bus 55 hier vers 18 h, entre la gare et le centre-ville. Il contient un cahier bleu et mes clés. Vous pouvez me joindre au 06 00 00 00 00. Merci."],
  ]),
  ...written(2,[
    ['ee21','B1','Télétravail','Le travail à domicile',"Écrivez un article court pour le journal de votre entreprise : le télétravail est-il une bonne solution ? Présentez des avantages et des limites.",25,['Organisez votre texte en paragraphes.','Donnez un exemple concret.'],['flexibilité','isolement','productivité'],"Le télétravail offre plus de flexibilité et réduit les déplacements. Par exemple, les employés peuvent mieux organiser leur journée. Cependant, il peut aussi créer de l’isolement. À mon avis, une formule mixte est la meilleure solution."],
    ['ee22','B1','Transport','Les transports publics',"Sur un forum local, vous répondez à la question : faut-il rendre les transports publics gratuits le week-end ? Donnez votre opinion.",25,['Annoncez votre position.','Ajoutez au moins deux arguments.'],['accessible','embouteillage','financer'],"Je suis favorable à la gratuité le week-end. Elle encouragerait les familles à laisser leur voiture et réduirait les embouteillages. En revanche, la ville doit prévoir un financement durable pour maintenir un service de qualité."],
    ['ee23','B2','Réseaux sociaux','Les réseaux sociaux et les adolescents',"Vous publiez un texte sur le site d’une association de parents. Expliquez comment utiliser les réseaux sociaux de manière responsable.",25,['Nuancez votre opinion.','Proposez des solutions.'],['protéger sa vie privée','modérer','sensibiliser'],"Les réseaux sociaux permettent de communiquer, mais ils exposent aussi les adolescents à des risques. Les parents et l’école devraient les sensibiliser à la protection des données et fixer des règles raisonnables. L’éducation reste plus efficace que l’interdiction totale."],
    ['ee24','B2','Éducation','L’éducation en ligne',"Rédigez une contribution : les cours en ligne peuvent-ils remplacer les cours en classe ?",25,['Comparez les deux possibilités.','Concluez clairement.'],['autonomie','interaction','complémentaire'],"Les cours en ligne facilitent l’accès à la formation et développent l’autonomie. Toutefois, ils ne remplacent pas totalement les échanges directs avec un enseignant. Je pense qu’ils doivent compléter les cours en classe, et non les supprimer."],
    ['ee25','B2','Intelligence artificielle','L’IA au travail',"Écrivez à votre équipe pour expliquer comment l’intelligence artificielle pourrait aider votre service, tout en précisant une limite importante.",25,['Restez concret.','Utilisez des connecteurs logiques.'],['automatiser','vérifier','confidentialité'],"L’intelligence artificielle pourrait automatiser les tâches répétitives et nous faire gagner du temps. Par conséquent, nous pourrions nous concentrer sur les clients. Cependant, toute information produite par l’outil devra être vérifiée afin de protéger la confidentialité."],
  ]),
  ...written(3,[
    ['ee31','B2','Environnement','Réduire les déchets',"Vous participez à un débat : les villes doivent-elles limiter fortement les emballages jetables ? Développez votre point de vue.",30,['Construisez une introduction, deux arguments et une conclusion.','Illustrez avec un exemple.'],['déchet jetable','inciter','recycler'],"Les villes devraient limiter les emballages jetables, car ils augmentent la quantité de déchets. D’une part, cette mesure encouragerait les commerces à proposer des alternatives réutilisables. D’autre part, elle sensibiliserait les citoyens. Une transition progressive aiderait les petites entreprises à s’adapter."],
    ['ee32','B2','Santé publique','La prévention',"Selon vous, les gouvernements doivent-ils investir davantage dans la prévention que dans les traitements médicaux ?",30,['Définissez l’enjeu.','Équilibrez les arguments.'],['prévention','dépistage','coût à long terme'],"Investir dans la prévention est essentiel, car le dépistage et l’information évitent certaines maladies et réduisent les coûts à long terme. Néanmoins, les traitements restent indispensables. Il faut donc renforcer la prévention sans diminuer les ressources consacrées aux soins."],
    ['ee33','B2','Éducation','Les devoirs à la maison',"Écrivez un texte argumentatif : les devoirs devraient-ils être supprimés à l’école primaire ?",30,['Employez des connecteurs variés.','Répondez à un contre-argument.'],['charge de travail','consolider','inégalités'],"Les devoirs peuvent consolider les apprentissages, mais ils accentuent parfois les inégalités entre les familles. À mon avis, ils devraient être courts et accompagnés d’explications. Ainsi, ils resteraient utiles sans pénaliser les élèves qui n’ont pas d’aide à la maison."],
    ['ee34','C1','Technologie','Les villes intelligentes',"Les villes intelligentes améliorent-elles réellement la qualité de vie ? Présentez une argumentation nuancée.",30,['Nuancez votre raisonnement.','Utilisez un registre soutenu.'],['données personnelles','optimiser','infrastructure'],"Les technologies urbaines peuvent optimiser les transports et l’énergie. Toutefois, elles soulèvent la question de la collecte des données personnelles. Leur déploiement ne sera bénéfique que s’il est transparent, contrôlé démocratiquement et accessible à tous les habitants."],
    ['ee35','C1','Changement climatique','Responsabilité individuelle et politique',"Face au changement climatique, la responsabilité individuelle est-elle suffisante ?",30,['Distinguez les niveaux de responsabilité.','Terminez par une proposition.'],['mesure structurelle','empreinte carbone','réglementer'],"Les gestes individuels sont nécessaires, mais insuffisants. Sans mesures structurelles concernant l’énergie, les transports et l’industrie, leur impact demeure limité. Les pouvoirs publics doivent réglementer, tandis que les citoyens soutiennent ces transformations par leurs choix quotidiens."],
  ])
];
