window.TCFData = window.TCFData || {};
const spoken = (task, rows) => rows.map(([id,niveau,theme,titre,situation,preparation,reponse,conseils,vocabulaire,exemple])=>({id,competence:'expression-orale',tache:task,niveau,theme,titre,situation,preparation,reponse,conseils,vocabulaire,exemple}));
window.TCFData.speaking = [
 ...spoken(1,[
  ['eo11','A2','Sport','S’inscrire à un club',"Vous souhaitez vous inscrire à une activité sportive. Posez des questions sur les horaires, le prix et le matériel.",60,120,['Posez au moins trois questions.','Utilisez des formules de politesse.'],['s’inscrire','cotisation','équipement'],"Bonjour, je voudrais m’inscrire au cours de yoga. Quels sont les horaires ? Combien coûte la cotisation ? Faut-il apporter un tapis ? Merci pour vos renseignements."],
  ['eo12','A2','Tourisme','Visiter un musée',"Vous êtes au bureau d’information touristique. Demandez des informations sur un musée de la ville.",60,120,['Présentez votre demande.','Précisez ce que vous cherchez.'],['tarif réduit','visite guidée','ouvert'],"Bonjour, pourriez-vous me dire si le musée des Beaux-Arts est ouvert demain ? Y a-t-il une visite guidée en français et un tarif réduit pour les étudiants ?"],
  ['eo13','B1','Logement','Louer un appartement',"Vous téléphonez à une agence pour obtenir des informations sur un appartement à louer.",60,120,['Demandez la superficie, le prix et la disponibilité.'],['loyer','charges','visiter'],"Bonjour, j’appelle au sujet de l’appartement annoncé près du métro. Quel est le loyer avec les charges ? Est-il encore disponible et serait-il possible de le visiter cette semaine ?"],
  ['eo14','B1','Transport','Louer un vélo',"Vous voulez louer un vélo pour une journée. Demandez les conditions au magasin.",60,120,['Utilisez des questions directes et indirectes.'],['caution','casque','itinéraire'],"Bonjour, je voudrais louer un vélo demain. Quel est le prix pour la journée ? Dois-je laisser une caution ? Est-ce que le casque est inclus ?"],
  ['eo15','B1','Culture','Participer à un atelier',"Vous contactez une bibliothèque pour vous inscrire à un atelier d’écriture.",60,120,['Indiquez votre niveau et votre disponibilité.'],['atelier','débutant','places disponibles'],"Bonjour, je suis débutant en écriture et je voudrais participer à votre atelier. Y a-t-il encore des places ? Est-il organisé le soir ou le samedi ?"],
 ]),
 ...spoken(2,[
  ['eo21','B1','Environnement','Convaincre un ami de recycler',"Votre ami ne trie jamais ses déchets. Vous essayez de le convaincre de commencer.",90,180,['Donnez des arguments simples.','Réagissez aux objections imaginées.'],['trier','poubelle de recyclage','gaspillage'],"Je comprends que cela semble compliqué, mais le tri prend seulement quelques minutes. Les emballages et le papier peuvent être recyclés. Si tout le monde fait un petit effort, on réduit beaucoup le gaspillage."],
  ['eo22','B1','Santé','Encourager une activité physique',"Un proche veut arrêter le sport faute de temps. Essayez de le convaincre de continuer.",90,180,['Proposez des solutions réalistes.'],['forme','habitude','marche rapide'],"Tu n’as pas besoin de faire une heure de sport chaque jour. Tu pourrais marcher vingt minutes après le travail ou prendre les escaliers. Cela aiderait ta santé et te permettrait de te détendre."],
  ['eo23','B2','Transport','Privilégier les transports publics',"Votre collègue utilise toujours sa voiture. Convainquez-le d’essayer les transports publics.",90,180,['Comparez les avantages.','Employez « pourtant », « donc », « en plus ».'],['embouteillage','abonnement','ponctuel'],"Les transports publics peuvent être plus pratiques que tu ne le penses. Tu éviterais les embouteillages et le coût du stationnement. En plus, avec un abonnement, tu pourrais lire ou travailler pendant le trajet."],
  ['eo24','B2','Éducation','Suivre une formation en ligne',"Votre sœur hésite à suivre une formation en ligne. Convainquez-la de l’essayer.",90,180,['Reconnaissez une limite avant de proposer une solution.'],['flexible','plateforme','accompagnement'],"C’est vrai qu’une formation en ligne demande de l’autonomie. Pourtant, elle te permettrait d’étudier selon ton horaire. Tu pourrais aussi choisir une plateforme avec des séances en direct pour garder un accompagnement."],
  ['eo25','B2','Culture','Assister à un festival local',"Vous souhaitez convaincre un ami de venir à un festival culturel dans votre ville.",90,180,['Donnez des arguments personnels et pratiques.'],['programmation','artiste local','ambiance'],"Ce festival est une excellente occasion de découvrir des artistes locaux. La programmation est variée et l’entrée est gratuite le dimanche. Je pense que l’ambiance te plairait, même si tu ne connais pas tous les groupes."],
 ]),
 ...spoken(3,[
  ['eo31','B2','Télétravail','Le télétravail est-il une bonne solution ?',"Exprimez votre opinion sur le télétravail pour les employés et les entreprises.",120,270,['Annoncez votre thèse.','Développez deux arguments et concluez.'],['conciliation','isolement','hybride'],"À mon avis, le télétravail est une bonne solution lorsqu’il est organisé de façon hybride. Il réduit les déplacements et facilite la conciliation entre vie professionnelle et vie personnelle. Toutefois, il peut isoler les employés. C’est pourquoi quelques jours au bureau restent utiles."],
  ['eo32','B2','Intelligence artificielle','L’IA dans l’éducation',"L’intelligence artificielle doit-elle être utilisée à l’école ?",120,270,['Nuancez votre réponse.','Donnez un exemple.'],['outil pédagogique','esprit critique','personnaliser'],"L’intelligence artificielle peut personnaliser les exercices et aider les élèves à progresser. Par exemple, elle peut expliquer une erreur immédiatement. Cependant, elle ne doit pas remplacer l’enseignant, qui guide l’élève et développe son esprit critique."],
  ['eo33','B2','Réseaux sociaux','Les réseaux sociaux font-ils plus de mal que de bien ?',"Présentez une réponse argumentée.",120,270,['Présentez les deux aspects puis votre position.'],['désinformation','lien social','modération'],"Les réseaux sociaux permettent de garder un lien social et de s’informer rapidement. Néanmoins, ils favorisent parfois la désinformation et la comparaison excessive. Ils sont donc utiles si les utilisateurs apprennent à vérifier les sources et à limiter leur temps d’écran."],
  ['eo34','C1','Économie','Faut-il limiter la publicité destinée aux enfants ?',"Développez un point de vue nuancé.",120,270,['Utilisez des connecteurs complexes.','Anticipez un contre-argument.'],['consommation','influencer','réglementation'],"La publicité peut influencer fortement les enfants, qui ne distinguent pas toujours l’information de la persuasion. Bien que les entreprises aient besoin de communiquer, une réglementation renforcée est justifiée pour les produits nocifs ou trop sucrés."],
  ['eo35','C1','Changement climatique','Les citoyens doivent-ils changer leur mode de vie ?',"Répondez de manière structurée et nuancée.",120,270,['Distinguez action individuelle et politique.'],['sobriété','mesure collective','transition'],"Les citoyens ont un rôle réel dans la transition, notamment par leurs choix de transport et de consommation. Toutefois, leur action ne peut suffire sans politiques publiques ambitieuses. La transition doit donc associer comportements individuels et mesures collectives."],
 ])
];
